
# get tide of one day
POST http://mds.nmdis.org.cn/service/rdata/front/knowledge/chaoxidata/list HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "serchdate": "2022-04-04",
    "sitecode": "T020"
}

# HTTP/1.1 200 OK
# Server: nginx/1.21.1
# Date: Mon, 04 Apr 2022 08:17:14 GMT
# Content-Type: application/json;charset=UTF-8
# Transfer-Encoding: chunked
# Connection: close
# Expires: 0
# Cache-Control: no-cache, no-store, max-age=0, must-revalidate
# X-XSS-Protection: 1; mode=block
# X-Content-Type-Options: nosniff
# Pragma: no-cache
# Access-Control-Allow-Credentials: true
# Access-Control-Allow-Headers: X-Requested-With
# Access-Control-Allow-Methods: GET,POST,OPTIONS,DELETE

# {
#   "success": true,
#   "msg": "",
#   "data": [
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "8151376678cd4d48b1cf9a0c95868ff3",
#       "recordtime": "2021-10-12 15:54:10",
#       "state": "1",
#       "sitecode": "T020",
#       "title": "秦皇岛",
#       "year": "2022",
#       "month": "4",
#       "coordinate": "   39°54′N119°36′E",
#       "timearea": "-0800",
#       "benchmark": "在平均海面下91cm",
#       "signature": "超级管理员",
#       "filedata": {
#         "a11": 76.0,
#         "cs1": "15:13",
#         "RecordTime": "2021-10-12 15:54:10",
#         "a10": 75.0,
#         "cs0": "06:47",
#         "a13": 76.0,
#         "cs3": "22:16",
#         "a12": 73.0,
#         "cs2": "18:01",
#         "a15": 101.0,
#         "a14": 90.0,
#         "a17": 88.0,
#         "a16": 97.0,
#         "a19": 87.0,
#         "ReportID": "5615735777594209636",
#         "a18": 84.0,
#         "cg1": 101.0,
#         "cg0": 51.0,
#         "cg3": 108.0,
#         "cg2": 84.0,
#         "ID": "5561527114925338715",
#         "a20": 94.0,
#         "a22": 107.0,
#         "a21": 102.0,
#         "a23": 106.0,
#         "a0": 84.0,
#         "a1": 80.0,
#         "a2": 89.0,
#         "a3": 90.0,
#         "a4": 76.0,
#         "a5": 62.0,
#         "a6": 54.0,
#         "a7": 51.0,
#         "a8": 58.0,
#         "a9": 68.0,
#         "Day": 4
#       },
#       "serchdate": "2022-04-04",
#       "inserttime": "2021-11-07 23:41:56"
#     }
#   ],
#   "page": {
#     "page": 1,
#     "pageSize": 20,
#     "total": 1,
#     "totalPage": 1,
#     "sort": null,
#     "order": null
#   },
#   "attr": {}
# }


###
# get provinces list
GET http://mds.nmdis.org.cn/service/rdata/front/knowledge/area/list?parentId=5010464519851424942 HTTP/1.1

# HTTP/1.1 200 OK
# Server: nginx/1.21.1
# Date: Mon, 04 Apr 2022 08:20:30 GMT
# Content-Type: application/json;charset=UTF-8
# Transfer-Encoding: chunked
# Connection: close
# Expires: 0
# Cache-Control: no-cache, no-store, max-age=0, must-revalidate
# X-XSS-Protection: 1; mode=block
# X-Content-Type-Options: nosniff
# Pragma: no-cache
# Access-Control-Allow-Credentials: true
# Access-Control-Allow-Headers: X-Requested-With
# Access-Control-Allow-Methods: GET,POST,OPTIONS,DELETE

# {
#   "success": true,
#   "msg": "信息操作成功!",
#   "data": [
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5359678358229842731",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "福建",
#       "areaenname": "Fujian",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 7
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5181903535968969393",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "广西",
#       "areaenname": "Guangxi",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 11
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5413705892610612211",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "广州",
#       "areaenname": "Guangzhou",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 9
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5625484080778443327",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "海南",
#       "areaenname": "Hainan",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 10
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "4975833679728738945",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "河北",
#       "areaenname": "Hebei",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 1
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5293027798039637126",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "江苏",
#       "areaenname": "Jiangsu",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 4
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5432072060831556751",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "辽宁",
#       "areaenname": "Liaoning",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 0
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5323306066487582247",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "山东",
#       "areaenname": "Shandong",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 3
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5653349478231077601",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "上海",
#       "areaenname": "Shanghai",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 5
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "4876987809364790815",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "台湾",
#       "areaenname": "Taiwan",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 8
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "4935741873097441187",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "天津",
#       "areaenname": "Tianjin",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 2
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "4845586374601047334",
#       "recordtime": "2017-01-12 13:56:58",
#       "areaname": "浙江",
#       "areaenname": "Zhejiang",
#       "pyname": "",
#       "parentid": "5010464519851424942",
#       "levelid": 1,
#       "sortindex": 6
#     }
#   ],
#   "page": null,
#   "attr": {}
# }

###
# get ports list
GET http://mds.nmdis.org.cn/service/rdata/front/knowledge/site/list?areaId=4975833679728738945 HTTP/1.1

# HTTP/1.1 200 OK
# Server: nginx/1.21.1
# Date: Mon, 04 Apr 2022 08:22:22 GMT
# Content-Type: application/json;charset=UTF-8
# Transfer-Encoding: chunked
# Connection: close
# Expires: 0
# Cache-Control: no-cache, no-store, max-age=0, must-revalidate
# X-XSS-Protection: 1; mode=block
# X-Content-Type-Options: nosniff
# Pragma: no-cache
# Access-Control-Allow-Credentials: true
# Access-Control-Allow-Headers: X-Requested-With
# Access-Control-Allow-Methods: GET,POST,OPTIONS,DELETE

# {
#   "success": true,
#   "msg": "",
#   "data": [
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "4613335436031122682",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T025",
#       "name": "岐口",
#       "enname": "QIKOU",
#       "pyname": "QK",
#       "coordx": 117.51666667,
#       "coordy": 38.60000000,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "4937642002698742152",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T026",
#       "name": "埕口外海",
#       "enname": "CHENGKOUWAIHAI",
#       "pyname": "CKWH",
#       "coordx": 118.43333333,
#       "coordy": 38.45000000,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "4942456691530852413",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T027",
#       "name": "黄骅港(一期煤码头)",
#       "enname": "HUANGHUAGANG(YIQIMEIMATOU)",
#       "pyname": "HHG(YQMMT)",
#       "coordx": 117.88333333,
#       "coordy": 38.31666667,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5309366417971387609",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T022",
#       "name": "京唐港",
#       "enname": "JINGTANGGANG",
#       "pyname": "JTG",
#       "coordx": 119.01666667,
#       "coordy": 39.21666667,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5409560625627481284",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T020",
#       "name": "秦皇岛",
#       "enname": "QINHUANGDAO",
#       "pyname": "QHD",
#       "coordx": 119.61666667,
#       "coordy": 39.91666667,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5430831130772778799",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T023",
#       "name": "曹妃甸",
#       "enname": "CAOFEIDIAN",
#       "pyname": "CFD",
#       "coordx": 118.50000000,
#       "coordy": 38.90000000,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5718208666494769492",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T019",
#       "name": "山海关",
#       "enname": "SHANHAIGUAN",
#       "pyname": "SHG",
#       "coordx": 119.81666667,
#       "coordy": 39.98333333,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     },
#     {
#       "page": 1,
#       "pageSize": 20,
#       "total": 0,
#       "totalPage": 1,
#       "sort": null,
#       "order": null,
#       "id": "5726313971389606983",
#       "recordtime": "2017-05-18 09:29:18",
#       "state": 1,
#       "code": "T021",
#       "name": "七里海(新开口)",
#       "enname": "QILIHAI(XINKAIKOU)",
#       "pyname": "PLH(XKK)",
#       "coordx": 119.28333333,
#       "coordy": 39.58333333,
#       "datatype": 1,
#       "areaid": 4975833679728738945
#     }
#   ],
#   "page": {
#     "page": 1,
#     "pageSize": 20,
#     "total": 0,
#     "totalPage": 1,
#     "sort": null,
#     "order": null
#   },
#   "attr": {}
# }

###
